version: "3.5"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3320:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_DATABASE: "gonnect"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
